-- Auto-generated from images on 2025-12-26T11:50:03
TRUNCATE TABLE product RESTART IDENTITY CASCADE;

INSERT INTO product (name, price, category, description, image_url) VALUES ('Chel Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the Chel Shoes collection.', '/images/chel_shoes/black_chel.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Chel Shoes (Oxblood)', 69.99, 'SHOE', 'Premium shoe from the Chel Shoes collection.', '/images/chel_shoes/oxblood_chel.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Chel Shoes (Red)', 69.99, 'SHOE', 'Premium shoe from the Chel Shoes collection.', '/images/chel_shoes/red_chel_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach1', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach1.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach2', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach3', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach3.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach4', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach4.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach5', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach5.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach6', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach6.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach7', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach7.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Coach Bag Coach8', 89.99, 'BAG', 'Premium bag from the Coach Bag collection.', '/images/coach_bag/coach8.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Hermes (Black)', 89.99, 'BAG', 'Premium bag from the Hermes collection.', '/images/hermes/hermes_black.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Hermes (Brown)', 89.99, 'BAG', 'Premium bag from the Hermes collection.', '/images/hermes/hermes_brown.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Hermes (Green)', 89.99, 'BAG', 'Premium bag from the Hermes collection.', '/images/hermes/hermes_green.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Hermes (Pink)', 89.99, 'BAG', 'Premium bag from the Hermes collection.', '/images/hermes/hermes_pink.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Hermes (Red)', 89.99, 'BAG', 'Premium bag from the Hermes collection.', '/images/hermes/hermes_red.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Hermes (White)', 89.99, 'BAG', 'Premium bag from the Hermes collection.', '/images/hermes/hermes_white.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited1', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited1.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited2', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited3', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited3.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited4', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited4.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited5', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited5.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited6', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited6.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Limited Shoes Limited7', 69.99, 'SHOE', 'Premium shoe from the Limited Shoes collection.', '/images/limited_shoes/limited7.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Black)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/black_loafer_2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Black)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/black_loafers.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Black)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/black_loafers_3.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Black)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/black_loafers_chain.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Black)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/black_loafers_pearl.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Cream)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/cream_color_loafer.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (Red)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/red_loafers.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Loafers (White)', 69.99, 'SHOE', 'Premium shoe from the Loafers collection.', '/images/loafers/white_loafers.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Long Bag (Black)', 89.99, 'BAG', 'Premium bag from the Long Bag collection.', '/images/long_bag/long_black.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Long Bag (Brown)', 89.99, 'BAG', 'Premium bag from the Long Bag collection.', '/images/long_bag/long_brown.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Long Bag (Green)', 89.99, 'BAG', 'Premium bag from the Long Bag collection.', '/images/long_bag/long_green.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Long Bag (Pink)', 89.99, 'BAG', 'Premium bag from the Long Bag collection.', '/images/long_bag/long_pink.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Long Bag (Red)', 89.99, 'BAG', 'Premium bag from the Long Bag collection.', '/images/long_bag/long_red.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Norm Bags Norm1', 89.99, 'BAG', 'Premium bag from the Norm Bags collection.', '/images/norm_bags/norm1.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Norm Bags Norm2', 89.99, 'BAG', 'Premium bag from the Norm Bags collection.', '/images/norm_bags/norm2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Saint Bags Saint1', 89.99, 'BAG', 'Premium bag from the Saint Bags collection.', '/images/saint_bags/saint1.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Saint Bags Saint2', 89.99, 'BAG', 'Premium bag from the Saint Bags collection.', '/images/saint_bags/saint2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Saint Bags Saint3', 89.99, 'BAG', 'Premium bag from the Saint Bags collection.', '/images/saint_bags/saint3.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Saint Bags Saint4', 89.99, 'BAG', 'Premium bag from the Saint Bags collection.', '/images/saint_bags/saint4.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Saint Bags Saint5', 89.99, 'BAG', 'Premium bag from the Saint Bags collection.', '/images/saint_bags/saint5.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sandal Heels (Gold)', 69.99, 'SHOE', 'Premium shoe from the Sandal Heels collection.', '/images/sandal_heels/gold_sandal_heel.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sandal Heels (Gold)', 69.99, 'SHOE', 'Premium shoe from the Sandal Heels collection.', '/images/sandal_heels/gold_sandal_heel_2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sandal Heels (Pink)', 69.99, 'SHOE', 'Premium shoe from the Sandal Heels collection.', '/images/sandal_heels/pink_sandal_heel.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sandal Heels (Red)', 69.99, 'SHOE', 'Premium shoe from the Sandal Heels collection.', '/images/sandal_heels/red_sandal_heels.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sandal Heels (Silver)', 69.99, 'SHOE', 'Premium shoe from the Sandal Heels collection.', '/images/sandal_heels/silver_sandal_heels.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Skin Bags 1', 89.99, 'BAG', 'Premium bag from the Skin Bags collection.', '/images/skin_bags/1.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Skin Bags 2', 89.99, 'BAG', 'Premium bag from the Skin Bags collection.', '/images/skin_bags/2.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Skin Bags 3', 89.99, 'BAG', 'Premium bag from the Skin Bags collection.', '/images/skin_bags/3.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Skin Bags 4', 89.99, 'BAG', 'Premium bag from the Skin Bags collection.', '/images/skin_bags/4.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Skin Bags 5', 89.99, 'BAG', 'Premium bag from the Skin Bags collection.', '/images/skin_bags/5.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Slip Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the Slip Shoes collection.', '/images/slip_shoes/slip_black.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Slip Shoes (Brown)', 69.99, 'SHOE', 'Premium shoe from the Slip Shoes collection.', '/images/slip_shoes/slip_brown.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Slip Shoes (Nude)', 69.99, 'SHOE', 'Premium shoe from the Slip Shoes collection.', '/images/slip_shoes/slip_nude.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Slip Shoes (Pink)', 69.99, 'SHOE', 'Premium shoe from the Slip Shoes collection.', '/images/slip_shoes/slip_pink.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sliper Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the Sliper Shoes collection.', '/images/sliper_shoes/black_slipper_shoe.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Sliper Shoes (Brown)', 69.99, 'SHOE', 'Premium shoe from the Sliper Shoes collection.', '/images/sliper_shoes/brown_slipper_shoe.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Stilettos (Black)', 69.99, 'SHOE', 'Premium shoe from the Stilettos collection.', '/images/stilettos/black_stil.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Stilettos (Black)', 69.99, 'SHOE', 'Premium shoe from the Stilettos collection.', '/images/stilettos/black_stil_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Stilettos (Brown)', 69.99, 'SHOE', 'Premium shoe from the Stilettos collection.', '/images/stilettos/brown_stil.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Stilettos (Brown)', 69.99, 'SHOE', 'Premium shoe from the Stilettos collection.', '/images/stilettos/brown_stil_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Stilettos (White)', 69.99, 'SHOE', 'Premium shoe from the Stilettos collection.', '/images/stilettos/white_stil.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Stilettos (White)', 69.99, 'SHOE', 'Premium shoe from the Stilettos collection.', '/images/stilettos/white_stil_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Summer Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the Summer Shoes collection.', '/images/summer_shoes/summer_black.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Summer Shoes (Blue)', 69.99, 'SHOE', 'Premium shoe from the Summer Shoes collection.', '/images/summer_shoes/summer_blue.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Summer Shoes (Green)', 69.99, 'SHOE', 'Premium shoe from the Summer Shoes collection.', '/images/summer_shoes/summer_green.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Summer Shoes (Nude)', 69.99, 'SHOE', 'Premium shoe from the Summer Shoes collection.', '/images/summer_shoes/summer_nude.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('Summer Shoes (White)', 69.99, 'SHOE', 'Premium shoe from the Summer Shoes collection.', '/images/summer_shoes/summer_white.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/black_blok.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/black_blok_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/v_black.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (Black)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/v_black_with_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (Pink)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/v_pink_with_leg.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (White)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/white_blok.jpeg');
INSERT INTO product (name, price, category, description, image_url) VALUES ('V Shoes (White)', 69.99, 'SHOE', 'Premium shoe from the V Shoes collection.', '/images/v_shoes/white_blok_leg.jpeg');
