-- Product catalogue. Matches the table Hibernate generated from Product.java.
CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(10, 2) NOT NULL,
    category    VARCHAR(255)   NOT NULL,
    brand       VARCHAR(255),
    color       VARCHAR(255),
    size        VARCHAR(255),
    stock       INTEGER,
    image_url   VARCHAR(255)
);
