-- Accounts. The app stores emails trimmed and lowercased; the CHECK keeps it that way,
-- so the UNIQUE constraint is effectively case-insensitive.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254)             NOT NULL,
    password_hash VARCHAR(255)             NOT NULL,
    display_name  VARCHAR(50)              NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_lowercase CHECK (email = LOWER(email))
);
