-- Orders belong to one user. Prices and names are copied from product at order time,
-- so later catalogue changes do not rewrite order history.
CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT                   NOT NULL REFERENCES users (id),
    payment_method VARCHAR(20)              NOT NULL,
    total          NUMERIC(12, 2)           NOT NULL,
    full_name      VARCHAR(100)             NOT NULL,
    phone          VARCHAR(30)              NOT NULL,
    address        VARCHAR(200)             NOT NULL,
    city           VARCHAR(100)             NOT NULL,
    country        VARCHAR(100)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_orders_payment_method CHECK (payment_method IN ('CARD', 'COD')),
    CONSTRAINT ck_orders_total CHECK (total >= 0)
);

CREATE INDEX ix_orders_user_id ON orders (user_id);

CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   BIGINT         NOT NULL REFERENCES product (id),
    product_name VARCHAR(255)   NOT NULL,
    image_url    VARCHAR(255),
    unit_price   NUMERIC(10, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    line_total   NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_order_items_quantity CHECK (quantity BETWEEN 1 AND 99)
);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);
